alias dots="cd $HOME/.dotfiles"
alias codots="code $HOME/.dotfiles"
alias py="python3"
alias docs="cd ~/Documents/"
alias repos="cd ~/misc/github/"
alias v="lvim"
alias downs="cd ~/Downloads/"
alias zconf="v ~/.zshrc"
alias ohmyzsh="v ~/.oh-my-zsh"
alias venv="source ./venv/bin/activate"
alias denv="deactivate"
alias e="E=pwd"
alias clean_py="find . | grep -E \"(/__pycache__$|\.pyc$|\.pyo$)\" | xargs rm -rf"
alias szsh="source ~/.zshrc"
alias ignition="cd ~/Desktop/designerlauncher/ && gio launch ~/Desktop/designerlauncher/designerlauncher.desktop && cd -"
alias startup="py $HOME/.dotfiles/startup.py"
